In [0]:
#数値というデータ型

In [1]:
print(type("hhh"))

<class 'str'>


In [3]:
print(type(1))

<class 'int'>


In [5]:
print(type(1.))
print(type(1.1))

<class 'float'>
<class 'float'>


In [0]:
import numpy as np
import scipy
from sklearn import datasets
#sklearn.py の中のclass datasetsをよむよ。

In [8]:
import numpy
numpy.array([1])

array([1])

In [10]:
import numpy as np
a_array = np.array([1])
a_array

array([1])

In [11]:
print(type(a_array))

<class 'numpy.ndarray'>


In [0]:
import tensorflow as tf

In [17]:
tf_array = tf.ones(2)
tf_array

<tf.Tensor 'ones_2:0' shape=(2,) dtype=float32>

In [18]:
type(tf_array)

tensorflow.python.framework.ops.Tensor

In [0]:
#数値型で遊んでみる

In [20]:
print(2+3-1)

4


In [21]:
print(2 + 3 - 1)

4


In [22]:
print(2*8)

16


In [23]:
#累乗　２の８乗
print(2**8)

256


In [24]:
print(2/8)

0.25


In [27]:
print(2%8)

2


In [28]:
#複雑な方に合わせる。5のintをfloatに合わせる
print(12.0/5)

2.4


In [29]:
import numpy as np
a_array = np.array([3])
b_array = np.array([2])
result = a_array * b_array
result

array([6])

In [30]:
import numpy as np
a_array = np.array(3)
b_array = np.array(2)
result = a_array * b_array
result

6

In [31]:
print(5*(2+3))

25


In [0]:
#数値型と文字列型の取り扱いの違い

In [33]:
print(type("39"))

<class 'str'>


In [34]:
print("I am 39 years old".find("39"))

5


In [35]:
print("I am 39 years old".find(39))

TypeError: ignored

In [36]:
print(29393929.find(39))

SyntaxError: ignored

In [37]:
print("I am 39 years old".find(str(39)))

5


In [38]:
x = "3"
y = "7"
print(int(x) + int(y))

10


In [0]:
#組み込み関数

In [40]:
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
seasons

['Spring', 'Summer', 'Fall', 'Winter']

In [41]:
type(seasons)

list

In [42]:
for s in seasons:
  print(s)

Spring
Summer
Fall
Winter


In [43]:
#enumerateはインデックスと値の組み合わせを返す
for i, s in enumerate(seasons):
  print(i, " ", s)

0   Spring
1   Summer
2   Fall
3   Winter


In [44]:
#zip　リストを2つ回る
for s1, s2 in zip(seasons, seasons):
  print(s1)
  print(s2)

Spring
Spring
Summer
Summer
Fall
Fall
Winter
Winter


In [46]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [0]:
#format

In [48]:
x = " John "
print("I am "+ x + ".")

I am  John .


In [49]:
x = " John "
print("I am {xx} .".format(xx=x))

I am  John  .


In [50]:
x = " John "
print("I am {xx}  {xx} {x2} .".format(xx=x, x2="!!"))

I am  John    John  !! .


In [52]:
x = " John "
print("I am {}  {}  .".format(x, "!!"))

I am  John   !!  .


In [54]:
x = " John "
print("I am {1}  {0}  .".format(x, "!!"))

I am !!   John   .


In [56]:
x = " John "
print("I am %s  ."%x)

I am  John   .


In [57]:
x = " John "
#%sは文字列
print("I am %s %s  ."%(x, "!!"))

I am  John  !!  .


In [60]:
x = " John "
#%dが数字
print("I am %s %d  ."%(x, 99))

I am  John  99  .


In [0]:
#改行　center ljust rjust

In [62]:
print("I am Joine. \n I am Happy.")

I am Joine. 
 I am Happy.


In [64]:
print("THE MAN".center(30))

           THE MAN            


In [65]:
#30文字ある中での右寄せ
print("THE MAN".rjust(30))

                       THE MAN


In [66]:
print("THE MAN".ljust(30))

THE MAN                       


In [67]:
#"""3つのでくくる
print("""
a
b
c

""")


a
b
c


